USE [master]
GO

/****** Object:  Database [GlossaryDb]    Script Date: 2/06/2021 10:29:32 AM ******/
CREATE DATABASE [GlossaryDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GlossaryDb', FILENAME = N'C:\Users\asifi\GlossaryDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GlossaryDb_log', FILENAME = N'C:\Users\asifi\GlossaryDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GlossaryDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GlossaryDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GlossaryDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GlossaryDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GlossaryDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GlossaryDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [GlossaryDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GlossaryDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GlossaryDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GlossaryDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GlossaryDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GlossaryDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GlossaryDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GlossaryDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GlossaryDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GlossaryDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GlossaryDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GlossaryDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GlossaryDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GlossaryDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GlossaryDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GlossaryDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [GlossaryDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GlossaryDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GlossaryDb] SET  MULTI_USER 
GO

ALTER DATABASE [GlossaryDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GlossaryDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GlossaryDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GlossaryDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GlossaryDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GlossaryDb] SET  READ_WRITE 
GO


USE [GlossaryDb]
GO

/****** Object:  Table [dbo].[glossaries]    Script Date: 2/06/2021 10:29:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[glossaries](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Term] [nvarchar](max) NOT NULL,
	[Definition] [nvarchar](max) NULL,
 CONSTRAINT [PK_glossaries] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO